spring:
  datasource:
    url: jdbc:h2:mem:peopledb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: warn
